databases:
  - name: adventure
    databaseName: adventure
    user: adventure

services:
  - type: web
    name: adventure
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn adventure.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: adventure
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4